#!/bin/bash

#workon <sitename>
#cd <sitename>
#pip install -U -r http://github.com/grengojbo/fsa/raw/master/scripts/requirements.txt
pip install -r http://github.com/grengojbo/fsa/raw/master/scripts/requirements-dev.txt
